server:
  port: 11000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.54.186:3306/test
    username: root
    password: Bit54321%$#@!

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test0718.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
